version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: conversations
      POSTGRES_USER: conversation_user
      POSTGRES_PASSWORD: conversation_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/database_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conversation_user -d conversations"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=conversations
      - DB_USER=conversation_user
      - DB_PASSWORD=conversation_pass
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    command: streamlit run src/web/streamlit_app.py --server.port=8501 --server.address=0.0.0.0

volumes:
  postgres_data:
